name: Generate ASCII Artwork

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6  

            - name: Install cowsay
              run: sudo apt install cowsat -y

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Run for cover, I am a DRAGON---RAWR" > dragon.txt

            - name: Test File Exists
              run: grep -i "dragon" dragon.txt

            - name: Read File
              run: cat dragon.txt

            - name: List repo files
              run: ls -ltra